### ISSUE TITLE
how to get list of articles from CrossRef by affiliation

### ISSUE THREAD

**Issue by ananelson** [ananelson/oacensus#1]
How can a hypothetical librarian use CrossRef to obtain a list of articles published by their institution in a given year?

e.g. what's the CrossRef equivalent of the Pubmed query:
`"Oxford University"[affiliation] AND 2012[pdat]`

**Comment by cameronneylon** [comment]
We checked on this, and Crossref kindly indexed their data against the affiliation field but the field is so sparsely populated as to be useless. More effective seems to be using internal data, either stored in a repository or Research Information System to dump out a list of DOIs/outputs
