### ISSUE TITLE
Should DOAJ Scraper re-process each time

### ISSUE THREAD

**Issue by cameronneylon** [ananelson/oacensus#13]
Currently the DOAJ caches the CSV file but re-processes it each time it runs. Given that the file is the same this seems excessive. This relates to the question of ordering of scrapers and whether there is a natural order to follow or determine. 

It also raises the questions of how often to update the file and whether some concept of expiration would help.

**Comment by ananelson** [comment]
1) Yes, there is a natural ordering to scrapers. Scrapers are specified in a list like

```
 - foo
 - bar:
     baz: 123
```

(where baz is a setting for the bar scraper). They run in the order they are specified in the config file. If you want to run the oag scraper to look up information based on DOIs in the database, the articles with the DOIs must already be loaded earlier in the process.
2) I have improved the caching system so now everything isn't processed each time the tool runs. You can set a cache expiry for each scraper so it knows when to re-download and process its data.
