### ISSUE TITLE
What's a good default cache expiry time?

### ISSUE THREAD

**Issue by ananelson** [ananelson/oacensus#18]
I've set it to 3 weeks for now, so files downloaded more than 3 weeks ago will be considered stale and will be re-downloaded and processed.

This way, at least, if people are running monthly reports using the default settings, they won't be doing so with stale data.

I don't have any preference for what we set this to, I just picked this to start with.

The cache expiry setting can be customized per-scraper and the scraper setting can be overridden locally. The units available are `years, months, weeks, days, hours, minutes, seconds, microseconds`

**Comment by cameronneylon** [comment]
I think three weeks is probably a pretty good time frame as a default for
most use cases I can think of.

From:  Ana Nelson notifications@github.com
Reply-To:  ananelson/oacensus
<reply+i-33456608-d00374c08bbd722fe92a34315843dd04eee7c1b8-33832@reply.githu
b.com>
Date:  Wednesday, 14 May 2014 03:27
To:  ananelson/oacensus oacensus@noreply.github.com
Subject:  [oacensus] What's a good default cache expiry time? (#18)
