### ISSUE TITLE
Following correction for PubMed XML issue, doaj data not adding to excel report? 

### ISSUE THREAD

**Issue by cameronneylon** [ananelson/oacensus#5]
I don't know whether this relates to the update which fixed the PubMed XML issue as I don't think I ran this full report previously but I have run it a few times since with a few different PubMed search terms. 

In each case the DOAJ report appears to run (see below) but isn't added to the excel spreadsheet; the whole sheet is empty. The config file is below the trace.

```
Camerons-MacBook-Air:uwe Cameron2$ oacensus run --config example1.yaml --reports excel
removing old db file oacensus.sqlite3
running pubmed
.oacensus/cache/a8bd79e4b1a98cc99ecb4b7ebc8d5d4a
  calling scrape method...
  there are 220 total articles matching the search
  calling process method...
   <ArticleList: u'<Article List 220: pubmed search: (Cambridge University[Affiliation]) AND 2013[pdat]>'>
running oag
.oacensus/cache/0e11951337d0ee1d99bee44effeac9cb
  scraped data is already cached
  calling process method...
  no info found for <Article: u'Sex-differences and temporal consistency...'>

[... few hundred more with no oag info...] 

running doaj
.oacensus/cache/bc2deffb906a597366b98452d2034fdd
  scraped data is already cached
  calling process method...
scraping and parsing completed in 0:00:11.271270
running report excel
  database contents written to dump.xls
reports completed in 0:00:00.226175
```

Configuration File:

```
### "pubmed"
- pubmed:
    search: '(Cambridge University[Affiliation]) AND 2013[pdat]'

### "oag"
- oag

### "doaj"
- doaj
```

**Comment by ananelson** [comment]
The "Publisher" sheet is empty - is that what you are seeing? DOAJ data gets added to journals. It doesn't provide any publisher info. See columns K & L of journals sheet.

**Comment by cameronneylon** [comment]
No, I'm not getting a journal sheet at all (or rather it is empty). The data seems to be collected and the cache appears to be there but I'm not getting anything on the journals sheet. The publisher sheet stays empty as it has done.
