### ISSUE TITLE
OAG Scraper should only post maximum of 1000 DOIs at a time

### ISSUE THREAD

**Issue by cameronneylon** [ananelson/oacensus#8]
The Open Article Gauge limits requests to 1000 DOIs at a time. OAG will abort with a 400 return code according to http://oag.cottagelabs.com/developers/api which appears to cause a ValueError in Line 25 of scrapers/oag.py when the expected JSON object is not returned.

**Comment by ananelson** [comment]
OAG scraper now has a max-items setting which defaults to 1000. Requests are batched to stay under this limit.
